### ISSUE TITLE
Remove warnings from R CMD check

### ISSUE THREAD

**Issue by rcannood** [xu-lab/SLICE#2]
Hello @xu-lab @mzguo @minzheguo!

I have recently been working with the SLICE package. Thank you for your contributions to the field! I noticed a problem with the package and decided to fork this repository, fix the problem, and have sent you a pull request (See PR #1). I hope you have time to review the pull request.

Kind regards,
Robrecht

**Comment by minzheguo** [comment]
Dear Robrecht,

Thanks a lot for the pull request. Sorry that I didn't notice the open
issue in the github slice project. Thanks for your efforts.
I shall check the pull request ASAP.

Thank you!

Best regards,

Minzhe

On Tue, Oct 17, 2017 at 3:29 AM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
Hello Minzhe,

Did you already have time to look at the pull request?

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue.
