### ISSUE TITLE
Insufficent genes for dimension reduction in getRDS

### ISSUE THREAD

**Issue by Roger-GOAT** [xu-lab/SLICE#4]
Hi team, great tool!
I transit my Seurat to SLICE and get an error in 'getRDS', would you mind giving some tips? Thanks!
```
es <- as.matrix(Seurat@assays$RNA@counts)
meta <- Seurat@meta.data

sc <- construct(exprmatrix=as.data.frame(es), 
                cellidentity=factor(meta$SCT_snn_res.0.3, levels=c('1','2','3','4','5','6',
                '7','8','9','10','11')),projname='Seurat')
data(mm_kappasim)

sc <- getEntropy(sc, km=km,            # use the pre-computed kappa similarity matrix of mouse genes
                 calculation="bootstrap",               # choose the bootstrap calculation
                 B.num=100,                             # 100 iterations
                 exp.cutoff=1,                          # the threshold for expressed genes
                 B.size=1000,                           # the size of bootstrap sample
                 clustering.k=floor(sqrt(1000/2)),      # the number of functional clusters  
                 random.seed=201602)                    # set the random seed to reproduce the results in the paper

plotEntropies(sc)

# perform PCA using the expression of predicted signature genes and with a high variance (greater than 8 variance in log2 FPKM) 
# The predicted signature genes are stored in FB.sig in FB.rda in the data folder 
Seurat <- SCTransform(Seurat,variable.features.n = 3000)
gene <- VariableFeatures(Seurat)
sc <- getRDS(sc, genes.use = gene,
             method="pca", 
             num_dim=2, log.base=2, 
             do.center=TRUE, do.scale=FALSE, 
             use.cor=TRUE, 
             min.var=8, min.cells=0)
Performing dimension reduction
Error in reduceExpressionSpace(object@data[which(object@genenames %in%  : 
  Insufficent genes for dimension reduction.
```
I try FB.sig or 1000 VariableFeatures, it gets the same error.
Thanks.

**Comment by zhongguodiyidao** [comment]
Hi
How to get mm_kappasim data?
thanks!

**Comment by acihanckr** [comment]
> Hi team, great tool! I transit my Seurat to SLICE and get an error in 'getRDS', would you mind giving some tips? Thanks!
> 
> ```
> es <- as.matrix(Seurat@assays$RNA@counts)
> meta <- Seurat@meta.data
> 
> sc <- construct(exprmatrix=as.data.frame(es), 
>                 cellidentity=factor(meta$SCT_snn_res.0.3, levels=c('1','2','3','4','5','6',
>                 '7','8','9','10','11')),projname='Seurat')
> data(mm_kappasim)
> 
> sc <- getEntropy(sc, km=km,            # use the pre-computed kappa similarity matrix of mouse genes
>                  calculation="bootstrap",               # choose the bootstrap calculation
>                  B.num=100,                             # 100 iterations
>                  exp.cutoff=1,                          # the threshold for expressed genes
>                  B.size=1000,                           # the size of bootstrap sample
>                  clustering.k=floor(sqrt(1000/2)),      # the number of functional clusters  
>                  random.seed=201602)                    # set the random seed to reproduce the results in the paper
> 
> plotEntropies(sc)
> 
> # perform PCA using the expression of predicted signature genes and with a high variance (greater than 8 variance in log2 FPKM) 
> # The predicted signature genes are stored in FB.sig in FB.rda in the data folder 
> Seurat <- SCTransform(Seurat,variable.features.n = 3000)
> gene <- VariableFeatures(Seurat)
> sc <- getRDS(sc, genes.use = gene,
>              method="pca", 
>              num_dim=2, log.base=2, 
>              do.center=TRUE, do.scale=FALSE, 
>              use.cor=TRUE, 
>              min.var=8, min.cells=0)
> Performing dimension reduction
> Error in reduceExpressionSpace(object@data[which(object@genenames %in%  : 
>   Insufficent genes for dimension reduction.
> ```
> 
> I try FB.sig or 1000 VariableFeatures, it gets the same error. Thanks.

Hello,

I was able to reproduce this error and it seems like min.var=8 too large of a threshold. Is there any reason for this choice? When I changed min.var=0.8 for example code runs for pbmc data with no issues.

Best

**Comment by acihanckr** [comment]
Hello,

After further investigation of this issue I realized that in the demo code, min.var is set to 8. However, the example data is not normalized hence gene expression variance 8 is a reasonable threshold. However, if you normalized the data before extracting the counts, no gene will pass this threshold.

Best
